# Generated by Django 5.2.6 on 2025-09-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
